server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instance-id: web-dept8083
    prefer-ip-address: true
spring:
  application:
    name: order-fegin
  resources:
    static-locations: classpath:/
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
info:
  app.name: web
  company.name: www.jk.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
